name: Run actions

on:
  push:
    branches:
      - dev
      - preprod
      - prod
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Some tests"
        run: |
          echo ${{ github.ref }}