name: Run actions

on:
  push:
    branches:
      - dev
      - preprod
      - prod
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Resolve branch_name"
        id: set_branch_name
        run: |
          branch_ref=${{ github.ref }}
          branch_name=${branch_ref/refs\/heads\//}
          echo "::set-output name=branch_name::$branch_name"
      - name: "Some tests"
        run: |
          echo ${{ steps.set_branch_name.outputs.branch_name }}
          